name: gecs-gdunit-test
run-name: ${{ github.head_ref || github.ref_name }}-gecs-gdunit-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.yml"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: gecs-gdunit-test${{ github.event.number }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: "GECS Tests"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      # run tests by using the gdUnit4-action with Godot version 4.2.1 and the latest GdUnit4 release
      - uses: godot-gdunit-labs/gdUnit4-action@v1.3.0
        with:
          godot-version: "4.5"
          paths: |
            res://addons/gecs/tests/
            res://addons/gecs_network/tests/
          timeout: 5
          report-name: test_report.xml
          arguments: "--quiet"
